# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Repository Dispatch
on:
  repository_dispatch:
    types: [my-event]
jobs:
  myEvent :
   runs-on: ubuntu-latest
   strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

   steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/download-artifact@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: artifacts
        path: node_modules
